---
version: '3'

services:
  user_db:
    image: mongo:5.0
    ports:
      - 27018:27017
  video_db:
    image: mongo:5.0
    ports:
      - 27017:27017
  web_api:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/web_api/Dockerfile
    ports:
      - 80:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=video_db
      - MONGO_PORT=27017
      - USER_HOST=user_service
      - USER_PORT=8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
  user_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/user_service/Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=user_db
      - MONGO_PORT=27018
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
 