---
version: '3'

services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
  web_api:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/web_api/Dockerfile
    ports:
      - 80:8000
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8000
      - MONGO_HOST=db
      - MONGO_PORT=27017
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  auth:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/authentication/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
 