---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  selector:
    matchLabels:
      api: web-api
  replicas: 1
  template:
    metadata:
      labels:
        app: web-api
        api: web-api
    spec:
      containers:
        - name: web-api
          image: jdvincent/video_api:latest
          env:
            - name: PROTOCOL
              value: {{ .Values.protocol | toJson  }}
            - name: HOST
              value: {{ .Values.host | toJson  }}
            - name: AUTH_HOST
              value: {{ .Values.auth_host | toJson  }}
            - name: AUTH_PORT
              value: {{ .Values.auth_port | toJson  }}
            - name: MONGO_HOST
              value: {{ .Values.mongo_host | toJson  }}
            - name: MONGO_PORT
              value: {{ .Values.mongo_port | toJson  }}
          ports:
            - name: web-api-a
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: web-api
  selector:
    app: web-api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-api
spec:
  ingressClassName: {{ .Values.ingress_class_name | toJson }}
  rules:
    - host: {{ .Values.ingress_host | toJson }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-api
                port:
                  number: 8000
